---
- name: Copy tmux.conf file
  copy: src=tmux.conf dest=~{{logname}}/.tmux.conf
      owner={{logname}} mode=0664 backup=yes
  tags:
    - tmux-development

#- name: Remove pre-exiting configurations
#  file: path=~{{logname}}/{{item}} state=absent
#  with_items:
#    - '.tmux'
#  tags:
#    - tmux-development
#
#- name: Install tmux config
#  shell: su - {{logname}}
#      -c 'git clone https://github.com/tony/tmux-config.git ~/.tmux'
#  tags:
#    - tmux-development
#
#- name: Download tmux submodule
#  shell: su - {{logname}}
#      -c 'cd ~/.tmux && git submodule update --init'
#  tags:
#    - tmux-development
#
#- name: Compile tmux submodule
#  shell: su - {{logname}}
#      -c 'cd ~/.tmux/vendor/tmux-mem-cpu-load && cmake . && make'
#  tags:
#    - tmux-development
#
#- name: Install tmux submodule
#  shell: cd ~{{logname}}/.tmux/vendor/tmux-mem-cpu-load && make install
#  tags:
#    - tmux-development
#
#- name: Create link to installed tmux.conf file
#  file: state=link
#        path=~{{logname}}/.tmux.conf
#        src=~{{logname}}/.tmux/tmux.conf
#        owner={{logname }}
#  tags:
#    - tmux-development

