---
- name: Remove pre-exiting Oh My Zsh installation
  file: path=~{{devuser}}/.oh-my-zsh state=absent
  tags: 
    - zsh-development

- name: Install Oh My Zsh
  git: clone=yes repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~{{devuser}}/.oh-my-zsh
  become_user: "{{devuser}}"
  tags: 
    - zsh-development

#- name: Copy Zsh rumtime command file
#  copy: src=zshrc dest=~{{devuser}}/.zshrc
#      owner={{devuser}} mode=0664 backup=yes
#  tags: 
#    - zsh-development

- name: Copy Zsh rumtime command file
  template: src=zshrc dest=~{{devuser}}/.zshrc
      owner={{devuser}} mode=0664 backup=yes
  tags: 
    - zsh-development

